before_install: 
 - cd IzdajMe
 - chmod +x mvnw
 - sudo service postgresql stop
 - sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
 - sudo chown postgres postgresql.conf
 - sudo mv postgresql.conf /etc/postgresql/10/main
 - sudo service postgresql start 10
before_script:
  - psql -c 'create database izdajme;' -U postgres
branches: 
  only: 
    - testing

addons:
  sonarcloud:
    organization: "milangovedarica15-1" # the key of the org you chose at step #3
    token:
      secure: "70d843b5a065c504240c45a0e000f772b2e9610a" # encrypted value of your token
  
language: java
services:
  - postgresql
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- ./mvnw test -B
- sonar-scanner